main: ${project.groupId}.${project.name}
name: ${project.name}
version: ${project.version}
website: ${project.url}
description: ${project.description}
authors: [Cayorion]
depend: [MassiveCore]
permissions:
  massivefx.*:
    children:
      massivefx.fxlist: true
      massivefx.selectorlist: true
      massivefx.do: true
  massivefx.fxlist:
    default: false
    description: list the available effects
  massivefx.selectorlist:
    default: false
    description: list the available selectors
  massivefx.do:
    default: false
    description: run an effect